### ISSUE TITLE
Implement full compile

### ISSUE THREAD

**Issue by ITRasmus** [d365collaborative/d365fo.tools#11]
We should implement the ability to do a partial compile with the tool

https://community.dynamics.com/ax/b/faheemahmeddynamicsax/archive/2016/11/21/use-command-line-to-build-your-dynamic-365-visual-studio-metadata-project-xppc

**Comment by Shind44** [comment]
it will be really usefull !
thanks for this this wonderfull tools !

**Comment by ITRasmus** [comment]
Are you missing something for the full compile there is already implemented? Or are you loooking for partial compile ?

**Comment by devax** [comment]
> Are you missing something for the full compile there is already implemented?
Are you saying that there is already a function available for full compile? If so, which one is it?

**Comment by Splaxi** [comment]
The only thing we have is the full database sync.

As per the post from the link, we have the XPPC.exe tool available, which is what Visual Studio is depending on. We can go several ways with that.

1. We simple investigate how to succeed with a compile for a given Visual Studio project, using the XPPC.exe tool. We should be able to learn something from the build server, because it depends on the Visual Studio projects folder. Inside some of the files in a project should be a list of modules that a given project has checked during development.

2. After some investigation we simply offer users the ability to pipe or list module names, that we prep into the XPPC.exe parameters and execute it. That puts the effort onto the user, that they need to understand what they want to be compiled.

@ITRasmus What is your take on this?

**Comment by ITRasmus** [comment]
I have just looked into it.
Visual studio relies on the Microsoft.Dynamics.Framework.Tools.BuildTasks.dll, file for compiling.
It basicly just takes the list of modules and then compiles them, but i has allso seperate functions for BestPractice test, Reports and so on.
I think we should go for Option 2, and then later we can use that for implementing a oneliner for full compile.

**Comment by Ievgenm** [comment]
Something like:
xppc.exe -metadata="k:\AosService\PackagesLocalDirectory" -modelmodule="Dimensions" -output="K:\AosService\PackagesLocalDirectory\Dimensions\bin" -referencefolder="k:\AosService\PackagesLocalDirectory"

**Comment by Ievgenm** [comment]
Here you go

using Microsoft.Dynamics.AX.Framework.Xlnt.ILGenerator;
using Microsoft.Dynamics.AX.Framework.Xlnt.XppParser.Pass2;
using System;
class Program
{
    const string PackagesLocalDirectory = @"k:\AosService\PackagesLocalDirectory";
    static void Main(string[] args)
    {
        string moduleToCompile = "Retail";
        ServiceMetadataProvider provider = new ServiceMetadataProvider(PackagesLocalDirectory, true, true, true, moduleToCompile);
        var modules  = provider.GetReferencedModules();
       
        foreach (var module in modules )
        {
            CompileModule(module);
        }

        CompileModule(moduleToCompile);

        Console.ReadLine();
    }

    static void CompileModule(string module)
    {
        Parameters parameters = new Parameters();
        parameters.XppMetadataPath = PackagesLocalDirectory;
        parameters.ModelModuleName = module;
        parameters.ReferencedAssembliesFolder = PackagesLocalDirectory;
        parameters.AssemblyOutputPath = System.IO.Path.Combine(PackagesLocalDirectory, module, "bin");
        ILGeneratorMain.Compile(parameters);
    }
}

**Comment by FH-Inway** [comment]
@Splaxi I think this issue can be closed since there is [Invoke-D365ModuleFullCompile](https://github.com/d365collaborative/d365fo.tools/blob/development/d365fo.tools/functions/invoke-d365modulefullcompile.ps1) since March 2019.
