### ISSUE TITLE
New database user added

### ISSUE THREAD

**Issue by skaue** [d365collaborative/d365fo.tools#140]
It seems a new user was introduced with v8. 
We need to support this.

Through SQL it is easy enough to catch.

`IF EXISTS (select * from sys.database_principals where type = 'R' and name = 'driuser')
BEGIN
    CREATE USER axdbreadonlyuser WITH PASSWORD = '@axdbreadonlyuser'
    EXEC sp_addrolemember 'driuser', 'axdbreadonlyuser'
END`

**Comment by Splaxi** [comment]
I say that we simply add it to the import, but make it mandatory = $false

The we write a big fat note somewhere, that if you are running on v8.x you have to fill it in.

**Comment by skaue** [comment]
I've made some changes to my fork, but it needs some testing. Shall we merge it with dev branch?

https://github.com/skaue/d365fo.tools/commit/f38a56ff6844c83d841d8af7d6cf701cad6b0b3c

**Comment by Splaxi** [comment]
Minor issue with some parameter that is in the list twice. Otherwise it looks great and should be capable to make it to the repo.

It will most likely fail based on some pester tests we have in place to protect the parameter set definition. But I will push an update back to your repo with what is needed.

**Comment by Splaxi** [comment]
0.4.82 release should contain it.
