### ISSUE TITLE
Switch-D365ActiveDatabase default parameter doesn't work

### ISSUE THREAD

**Issue by GeoffreyDelmee** [d365collaborative/d365fo.tools#193]
Looking at the help, it seems 'NewDatabaseName' parameter doesn't need an explicit switch and is also the only one as is.

Running 'Switch-D365ActiveDatabase AxDB_imported' will ask for parameter 'NewDatabaseName'.
Running 'Switch-D365ActiveDatabase -NewDatabaseName AxDB_imported' will work fine.

This have been repro in 0.5.4.
![switch-d365activedatabase](https://user-images.githubusercontent.com/37577853/53424853-48e7fa80-39e4-11e9-8191-3c588c437785.png)

**Comment by Splaxi** [comment]
Hi Geoffrey!

If you run a `Get-Help Switch-D365ActiveDatabase -Full`, you will see that the parameter is actually mandatory. **Required? True** 

```
    -NewDatabaseName <String>
        The database that takes the DatabaseName's place

        Required?                    true
        Position?                    6
        Default value
        Accept pipeline input?       false
        Accept wildcard characters?  false
```

What you are doing when parsing the value for the **NewDatabaseName** directly to the function / cmdlet, you are invoking the positional parameter mechanism. You can read more about that here: [about_Functions_Advanced_Parameters](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_functions_advanced_parameters?view=powershell-6#position-argument)

If you look closely at the output earlier, you can see that the **NewDatabaseName** parameter is not the first positional parameter and the explains why it doesn't work. Either you have to fill in all other parameter values (then you would lose some of the default values that we actually provide) or simply use the parameter name as you have shown works.

We encourage the use of parameter names explicitly, because is takes away the confusion when you are going to share your scripts with colleagues and peers. At the moment we don't have it on our road map to review all functions / cmdlets and see if we could move some of the parameters around.

You are welcome to do a PR for this function, where you update the parameter section and look into the different parameters positional values and make it work for your use case. Then we can see if that breaks anything in the unit tests and make it part of the module.

**Comment by GeoffreyDelmee** [comment]
Hello,

thanks a lot for the explanation on the positional parameter.
I totally get it's better to use explicit parameters for scripting purpose.
In my case, I was running it from command line and as it seemed to be the only mandatory element, I though it would work.
I'm new to github so, I'll try to make a push request to move the only mandatory parameter at the first place in order to facilitate "command-liners" use, nor only tool makers :)

**Comment by Splaxi** [comment]
Hi again!

You should totally visit our [wiki](https://github.com/d365collaborative/d365fo.tools/wiki) and especially the [Getting Started With GitHub](https://github.com/d365collaborative/d365fo.tools/wiki/Getting-Started-with-GitHub) & [Your First Pull Request](https://github.com/sqlcollaborative/dbatools/wiki/Your-First-Pull-Request)

Most of our wiki pages has been "borrowed" from the PowerShell module [dbatools](https://dbatools.io), because they made great guides.

The most important tasks you have a head of you are:

- Install [GitHub Desktop](https://desktop.github.com)
- Fork our project from the **Development** branch - **NOT** the master branch
- **Clone** your fork (also known as your own repository) to a local folder on your machine
- Code the changes that you need to do
- **Test** your code changes
- Commit all your changes
- Push your changes to your **own** repository (the fork you created earlier)
- Visit your fork / repository on github and create a **Pull Request** against our **development**

If you need any assistance with that, let me know and I'll take my time to help you out. You can catch me on twitter (@Splaxi).

I expect that you speak French based on your linkedin profile, so maybe @Shind44 (Charles) could be a good resource for assistance, because he did do pull requests and speaks French (Bonjour Charles!!)

**Comment by Shind44** [comment]
Bonjour Mötz !

happy to help if need

unfortunatelly no times last weeks to develop new features on my favorite tools :) 

however i'm trying to go in the Amsterdam AXUG event, if i remember you will be a speaker of a session :)

**Comment by Splaxi** [comment]
@GeoffreyDelmee 

Will you look into this or can I simply close the issue?

You are welcome to create a PR like described and push it to the repository, then we will have a look at it.

Will auto close end of week, if no further development.
