### ISSUE TITLE
Enhance Invoke-D365DBSync help to describe SyncMode possibilities

### ISSUE THREAD

**Issue by GeoffreyDelmee** [d365collaborative/d365fo.tools#194]
Looking at the full help for Invoke-D365DBSync cmdlet, we don't have a lot of elements for SyncMode parameter. We just have the default mode:

```
    -SyncMode <String>
        The sync mode the sync engine will use

        Default value is: "FullAll"

        Obligatoire ?                false
        Position ?                   4
        Valeur par défaut                     FullAll
        Accepter l'entrée de pipeline ?       false
        Accepter les caractères génériques ?  false
```

Looking at the script, the validation set contains a lot more values:

```
        [Parameter(Mandatory = $false, Position = 3)]
        #[ValidateSet('None', 'PartialList','InitialSchema','FullIds','PreTableViewSyncActions','FullTablesAndViews','PostTableViewSyncActions','KPIs','AnalysisEnums','DropTables','FullSecurity','PartialSecurity','CleanSecurity','ADEs','FullAll','Bootstrap','LegacyIds','Diag')]
        [string]$SyncMode = 'FullAll',
```

It would be interesting to have the overall list and their action in the help.

**Comment by Splaxi** [comment]
Hi,

You totally hit one of our weak spots with this one!

We started out believing that we could utilize the syncengine for several use cases, but the more we played with it and the more we started doubting where we would end up. We had some chats and talks with several Microsoft employees that knows a fair bit about the compiler and syncengine. We learned that with the lock down of permissions on the Microsoft hosted developer environments would create even more work for us selves.

From an Application Lifecycle Management (ALM) point of view, what we are trying to fix with this module is to enable people to automate their daily life even more and better than possible with the tools made by Microsoft.

With that context, what use cases do we have for synchronization? We need to synchronize the database when we move it around as a bacpac file and switch out the old database with the new one. Other than that, we would just have to try and support things that maybe or maybe not be of value for the community. But if you can test any of the other options and prove it works, and actually solves an use case, we will gladly help you with making that part of the list of options. But just listing the options and making them easy available, would potentially hit us like a boomerang, where our issue list would grow into reports about different sync modes not working.

So, just to be very clear. If you want to test any other syncmode, you can simply pass the string value to the -SyncMode parameter. We **could** display all the options for the user, but by doing that, we take a risk and actually have to support all these syncmodes and we don't even know if they work, little less do we know what they **actually** are doing. Remember, we are not part of Microsoft, so we are poking around, playing with the bits and bytes, and sometimes we break stuff, in order to learn more. We settled for the FullAll syncmode, because that use case is solid - we need to sync after we switch out the database. 

Please keep coming with all the questions and please push back on what we are saying if you don't agree. We are learning along the way, and we have changed our minds several times, but also spend a lot of hours on something that didn't have a real use case. So we try to vet things a bit more these days and looking 3-6 months into the future and asking if the use case is real or not.

I hope you still find interest in the module 🤞

**Comment by GeoffreyDelmee** [comment]
Don't worry, I'm very interested in this module. And for elements I may miss, I'm willing to contribute. It will also allow me to put my hands in PowerShell.

I was looking at options on the SyncMode as I have a local VM on my laptop and updating it to 8.1.3 PU23, the sync db step fails because of the timeout. I was then looking for the minimal db synch or to split in several steps in order not to reach the timeout.

**Comment by Splaxi** [comment]
@GeoffreyDelmee

Can we close this one? Should we do anything about the other options, let us team up.

**Comment by GeoffreyDelmee** [comment]
Sorry for the delay. I've been off the grid last week.
