### ISSUE TITLE
Import

### ISSUE THREAD

**Issue by turbozapekanka** [d365collaborative/d365fo.tools#297]
Example in docs is below:

Import-D365Bacpac -ImportModeTier2 -SqlUser "sqladmin" -SqlPwd "XyzXyz" -BacpacFile "C:\temp\uat.bacpac" -AxDeployExtUserPwd "XxXx" -AxDbAdminPwd "XxXx" -AxRuntimeUserPwd "XxXx" -AxMrRuntimeUserPwd "XxXx" -AxRetailRuntimeUserPwd "XxXx" -AxRetailDataSyncUserPwd "XxXx" -AxDbReadonlyUserPwd "XxXx" -NewDatabaseName "ImportedDatabase"

Two questions:
1) How does it know which Azure SQL database (Tier2) to import to?
2) How it can overcome the IP address block?

Please update docs with more details

**Comment by Splaxi** [comment]
1. It knows based on the web.config file that is present on the VM that you are running the command from. This is actually the main driver of the module, that we grab as much as we can. You can overwrite the defaults by specifying the remaining parameters available from the cmdlet. 

2. We cannot overcome the IP block, other than you make sure that SSMS is capable of connecting to the Azure SQL DB, from the same machine, then the tools will also be able to connect.

**Comment by turbozapekanka** [comment]
So Tier2 import must be run on the same machine where Tier2 AOS is running. This was not clear from documentation.

**Comment by Splaxi** [comment]
In theory that is not correct.

If you have every single piece of software available and the IP block is in place, then importing the database into the Azure SQL DB should work from any machine in the world. You should also be able to do the switching of the databases from any machine in the world.

You **cannot** run a synchronization against the database from any other machine than an AOS server. And we all know how important the synchronization of the database is, so that step is actually the real reason why it makes sense to only run a Tier2 import from an AOS server.
