### ISSUE TITLE
Would be nice to have an undo swith command

### ISSUE THREAD

**Issue by turbozapekanka** [d365collaborative/d365fo.tools#298]
To roll back changes made by Switch-D365ActiveDatabase and restore original AxDB

**Comment by Splaxi** [comment]
You can list all databases. 

So you simply run a switch, with the names in the reverse order...

**Comment by turbozapekanka** [comment]
I tried, it does not work when the new database name is "AxDB_Original"

**Comment by Splaxi** [comment]
Reading the docs:

https://github.com/d365collaborative/d365fo.tools/blob/development/docs/Switch-D365ActiveDatabase.md

You should be able to put any new name for the db that you want to switch out. 

So if the new db is named axdb_original, you should be able to pass -NewDatabaseName "Back To Scratch" and then it should work...

**Comment by turbozapekanka** [comment]
So I have AxDB and AxDB_Original
I wanted to switch back to original and pass -NewDatabaseName "AxDB_Original" - it tries to rename AxDB to AxDB_Original and sure enough it fails because a database with that name already exist.

**Comment by Splaxi** [comment]
Sorry!

I see what you mean. Yes, the new database has to be named anything else, than axdb_original...

We keep discussing these issues. The module is there to help and assist with D365FO things. Switching out the database is one of the things.

But fixing mistakes with names and stuff we actually recommend to utilize the dbatools.io module, because it is a database only module, with far more advanced capabilities than our module.

So I would recommend that you dig into the dbatools.io module to rename the database.

The story is the same with offering native sql backups. Use the dbatools.io for that, to get a module with the right focus...
