### ISSUE TITLE
Stop-D365Environment does not work

### ISSUE THREAD

**Issue by turbozapekanka** [d365collaborative/d365fo.tools#299]
PS C:\Users\Adminf66cddf654> Stop-D365Environment -verbose
VERBOSE: [16:48:00][Get-ServiceList] The PSBoundParameters was
VERBOSE: [16:48:00][Stop-D365Environment] Working against: TTIDemo-1 - stopping services
VERBOSE: [16:48:00][Stop-D365Environment] Working against: TTIDemo-1 - listing services
VERBOSE: [16:48:00][Stop-D365Environment] Results are:

Server               DisplayName                                                  Status     Name
------               -----------                                                  ------     ----
TTIDemo-1            Microsoft Dynamics 365 Unified Operations: Batch Manageme... Running    DynamicsAxBatch
TTIDemo-1            Microsoft Dynamics 365 Unified Operations: Data Import Ex... Running    Microsoft.Dynamics.AX.F...
TTIDemo-1            Management Reporter 2012 Process Service                     Running    MR2012ProcessService
TTIDemo-1            World Wide Web Publishing Service                            Running    w3svc

PS C:\Users\Adminf66cddf654>

**Comment by turbozapekanka** [comment]
Only works if PowerShell is Run as Administrator

**Comment by Splaxi** [comment]
This is expected behavior. 

Try stopping / starting services from either ordinary command line or powershell, and see what they require from you...

**Comment by turbozapekanka** [comment]
Today it does not work ever with Run as Administrator Poweshell window:
Tried three times

Windows PowerShell
Copyright (C) 2016 Microsoft Corporation. All rights reserved.

PS C:\windows\system32> Stop-D365Environment

Server               DisplayName                                                  Status     Name
------               -----------                                                  ------     ----
TTIDemo-1            Microsoft Dynamics 365 Unified Operations: Batch Manageme... StartPe... DynamicsAxBatch
TTIDemo-1            Microsoft Dynamics 365 Unified Operations: Data Import Ex... Stopped    Microsoft.Dynamics.AX.F...
TTIDemo-1            Management Reporter 2012 Process Service                     Stopped    MR2012ProcessService
TTIDemo-1            World Wide Web Publishing Service                            Stopped    w3svc


PS C:\windows\system32> Stop-D365Environment

Server               DisplayName                                                  Status     Name
------               -----------                                                  ------     ----
TTIDemo-1            Microsoft Dynamics 365 Unified Operations: Batch Manageme... Running    DynamicsAxBatch
TTIDemo-1            Microsoft Dynamics 365 Unified Operations: Data Import Ex... Stopped    Microsoft.Dynamics.AX.F...
TTIDemo-1            Management Reporter 2012 Process Service                     Stopped    MR2012ProcessService
TTIDemo-1            World Wide Web Publishing Service                            Stopped    w3svc


PS C:\windows\system32> Stop-D365Environment

Server               DisplayName                                                  Status     Name
------               -----------                                                  ------     ----
TTIDemo-1            Microsoft Dynamics 365 Unified Operations: Batch Manageme... Running    DynamicsAxBatch
TTIDemo-1            Microsoft Dynamics 365 Unified Operations: Data Import Ex... Stopped    Microsoft.Dynamics.AX.F...
TTIDemo-1            Management Reporter 2012 Process Service                     Stopped    MR2012ProcessService
TTIDemo-1            World Wide Web Publishing Service                            Stopped    w3svc


PS C:\windows\system32>

**Comment by Splaxi** [comment]
Please remember that Microsoft has configured the batch service to recover from unexpected failures / stoppings, so your developer box will actually restart the batch service. This can be validated that if you see that the batch service has been stopped, but 1 minute later it is started / running, then the service was recovered.

If every other service than batch is stopped, then you have hit the magical "Batch cannot be stopped" issue. 

Some developer boxes gets this issue, randomly. We have seen installation of updates break, because you are unable to stop the batch service. Try and do it from the Services list from the GUI - there you will get the same error.

But if you kill it from the task manager, or simply restarts the entire VM, then you should be able to control it again.

So to be clear, this issue is not with the tools - but that something is blocking the batch service it self to actually stop and there fails, regardless of using the GUI, Powershell or old school commandline commands.

**Comment by turbozapekanka** [comment]
Yes, I had to restart the VM, then it worked.
