### ISSUE TITLE
get-d365installedhotfix not listing any hotfixes

### ISSUE THREAD

**Issue by JoPe72** [d365collaborative/d365fo.tools#313]
I have a 10.0.4 with an added package of quality hotfixes. When i run get-d365installedhotfix I do not get a list of installed hotfixes back. There is no error message but there is no result either.

**Comment by FH-Inway** [comment]
@Splaxi I wonder if this cmdlet is still relevant. The addins function that @Ievgenm describes in their blog does not seem to exist anymore. I think hotfixes in this sense may have been something from the pre one version era.

**Comment by Splaxi** [comment]
@FH-Inway 

I believe you are correct. We had a brief discussion way back with Joris and he stated the same thing.

Should do a refactor and remove them, so we only have used / valid cmdlets available?

**Comment by FH-Inway** [comment]
@Splaxi No arguments against removal from me, our projects are all on one version. But I hear there are still environments out there that are not (probably mostly on premise). Do you have any indication if the d365fo.tools are used on those?

Instead of removing, we could improve the cmdlets documentation to let users know that it is intended for older versions. But I'm not sure if it is worth the effort. Maybe the tools should have some sort of [deprecation warning](https://github.com/PowerShell/PowerShell/issues/11674)?

**Comment by Splaxi** [comment]
I'm favor for deprecation warnings.

Let's settle for 6 months.

The tools are not used to much, as they have other other tools (public) from other community members.

Would you take a swing at a PR?

**Comment by Ievgenm** [comment]
Im not 100% sure that it is obsolete. ER takes dependencies on HF installed so it checks if they are installed or not. I need to look into it and see what it does.

**Comment by Splaxi** [comment]
@Ievgenm Any news to share with us? 😉

**Comment by Ievgenm** [comment]
Gave it a quick look and did not find anything useful, so probably just deprecate it.

**Comment by Splaxi** [comment]
Closing because of age
