### ISSUE TITLE
Change style of PS functions to be more compatible with Azure DevOps

### ISSUE THREAD

**Issue by AlexHimself** [d365collaborative/d365fo.tools#353]
This issue ideally is a discussion, and is not exactly simple, but would make the entire d365fo tool-set far more valuable to the community in my opinion.

I think functions being created going forward, and existing functions should be updated in a way to be more compatible with Azure DevOps (ADO) Pipelines so they can be more easily incorporated into environment management via [ADO Local Agent](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/v2-windows?view=azure-devops) + [Powershell tasks](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/powershell?view=azure-devops).

This would allow quickly installing/configuring a local agent on pretty much any machine where PS can be run, configuring things like [Variable groups](https://docs.microsoft.com/en-us/azure/devops/pipelines/library/variable-groups?view=azure-devops&tabs=yaml) and then management tasks would be simpler, more automated, and more consistent...and ultimately would be baked more naturally into D365FO and with Microsoft's ADO vision.

An example of more _"friendly"_ to ADO Powershell code, where upon an issue, it is logged more appropriately back to ADO is below:

```
try {
	# Do Something
}
catch {
	Write-Host "##vso[task.logissue type=warning;] There was an error doing <something>. Please review..."
}
```

Some other things to consider are incorporating environment variables, uploading misc files back, etc.

**Comment by Splaxi** [comment]
Hi Alex,

Thanks for taking the time to provide some feedback on a higher level than just requesting support for X feature!

The module was never intended to be aware of Azure DevOps (AZDO) and therefore we never looked that way.

I see several ways where we can make this work, without having to do a major overhaul of the module. We have the `Enable-D365Exception` function, which will enable the core functions that are running some of the important worksloads, to throw full fledged exceptions at you. This puts the effort of try-catch and `Write-Host "##[task.logissue type=warning;]"` on to you as the DevOps engineer, that have this wish / requirement. We might need to update a few functions, to fully support the exceptions when needed, but that journey is already started and is easy to continue on.

Pros: 
- It keeps to module unaware of the outer environment, which a huge factor for me and where I see the module going.
- People needed this capability will be given a documented / guided approach to achieve the desired out come.

Cons:
- We push the development effort onto the single DevOps engineer.

A hack / work around could be that you simply redirects the Write-Host output into a file / variable. You would lose the real time aspects of the process / progress running, but it could work.

Next suggestion: Because the module is based on the PSFramework, we have some options in place to have a configuration, that indicates if you want Write-Host / Write-Verbose to support Azure DevOps (AZDO). We should be able to identify the top 10 functions we want to support this, run through them and have their different Write-* updated to check if the VSO configuration is set or not.

Pros:
- Is will not break how the module behaves outside of Azure DevOps (AZDO)
- Over time the DevOps Engineer will only have to enable the Azure DevOps output syntax support once per step in his pipeline and from there it will just work

Cons: 
- Initial overhead of implementation of the mentioned configuration
- Initial overhead of refactor of the different functions to support Azure DevOps output syntax

The last suggestion: We reach out to Fred, the mastermind behind the PSFramework and see how we would make it possible to support a "Azure DevOps" prefix configuration, so that we move the development task into his module and simple configure it run time and then all our functions will support it without any refactoring.

Pros:
- The development effort is minimized inside the module
- Pushing the configuration to PSFramework will make it seamless for any future development in our module, to support Azure DevOps (AZDO) output syntax.

Cons:
- Fred might decline our request
- We might need to do all the work needed in his module and meet his quality requirements, which could prove hard (he has VERY high standards)

This was the messaging / output syntax feedback on your request. The variables will come in the next comment 😉

**Comment by AlexHimself** [comment]
As I'm pretty green to the D365 tools, I'm going to rely on you/Fred to think out how the logistics of the idea could work. And there are many aspects to consider, but I'll stay focused on the output/logging aspect below.

One thing to note, from PS there are ways to reflect and determine `if` the script is being executed by AZDO or not. This could be possibly be combined with PS's [Dynamic Parameters](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_functions_advanced_parameters?view=powershell-6#dynamic-parameters) to modify some sort of behavior.

Or alternatively given that, one way I've seen Microsoft do this and it's more of a general framework approach, is they create a logging function of some sort, and instead of `Write-Host`, `Write-Verbose`, etc...every function calls the logging function, and the logging function can determine if we're running from AZDO and output based on that. And of course the logging function could have all sorts of optional parameters too.

Another idea, which I'm guessing PS can do but I don't know off hand is some sort of `abstract` PS class that all PS functions extended...in effect I think it'd be useful to create a custom [Common Parameter](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_commonparameters?view=powershell-6) of sorts.

One method could also be to have all functions have some sort of `init` call that determines their behavior.

Ultimately the way it stands with this tool-set it seems, is devs cobble together a bunch of "routine" PS scripts and put them in a folder. I think AZDO as a command-center could lead to a more **corporate** adoption. Just spitballing some ideas.

**Comment by Splaxi** [comment]
I have done the first draft of a PR for the PSFramework module, that should enable us to leverage the Write-PsfMessage function. At the moment you need to enable the prefix once per powershell task in your pipeline. Let see if Fred and I can come to an agreement on the implementation details.

I want to spend some time on how I see the Azure DevOps logging request fit in to the module and how the road map looks.

The module is intended as a daily tool, that assists and helps the technical people in a D365FO project. The module is built to wrap around standard Microsoft solution and documentations, to be sure that we can replicate things and get support from Microsoft.

This means that the focus of the module is to help with automation whenever possible and that is should be easier than the standard tools available from Microsoft. The different bacpac processes with SqlPackage.exe is the most clear example of that.

This translates into the fact that I'm all ears for making it possible to orchestrate things from Azure DevOps easier and better than we already are doing, but it will not be my primary focus. Adding support for logging tags, that will assist you when messages are being written to the host / console, is a small feat (when I'm done with Fred).

Support for variables on the other hand, using the Azure DevOps tags, where you specify a variable and put the variable value into the message that is written to the host / console, that will most likely not be implemented. Anything that the different functions can and will output, you can catch in a variable, and then you as the Azure DevOps engineer are free to use Write-Host (Write-PsfMessage -Level Host") to get that in place.

The way that all functions exposes all parameters, gives you the opportunity to pass pipeline variables to it. Either with some inline PowerShell magic or simply "persist" the value directly to a local variable in your script and have that passed to the function as the parameter.

As long as a function can be run directly, just by passing the right parameters, it will also be able to run in Azure DevOps. This goes for hosted agents, and local on-prem agents. Personally I have several pipelines running, where the code is 100% identical across multiple customers and projects, where everything is configured in the variables of the pipeline.

I know of people that are using the Azure Release Pipeline, together with the tools, where they move around bacpac files and have them imported, prepped, switched out and fully synced. Again, all the parameter details are stored in the variables for the pipeline and they had to pass that into the different functions.

Variable Groups for me should just be more of the same, when the pipeline is running, then they would be available just like ordinary pipeline variables and you should be able to pass them into the desired parameters of a given function.

I'm very keen on making sure that the module should ignore what environment it will be running in. From my point of view it opens up for using the module in any context where you can make it work, to fit your needs. If you choose to run it in Azure DevOps, that is fine. We'll make sure that the different functions will just work, if you pass the correct parameters to it.

I want to empathize: I really appreciate your inputs and feedback, it is nice the see people thinking about other ways to utilize the module going forward. So please don't take my push back as my not listing or not trying to understand, but merely trying to focus on what the module is born to solve.

**Comment by AlexHimself** [comment]
Great thoughts. I think I need to play around with the tools more to see how they work with ADO.

**Comment by Splaxi** [comment]
Let me know if you want to do a session, where I give you a grand tour 😉
