### ISSUE TITLE
Suggestion: Consider split this up in multiple lines to avoid horizontal scrolling

### ISSUE THREAD

**Issue by skaue** [d365collaborative/d365fo.tools#40]
This is more of a developer preference thing, trying to avoid code that requires horizontal scrolling. 

https://github.com/d365collaborative/d365fo.tools/blob/1867a38fb8bcd9c301ebbd311ec4f89a504956dd/functions/import-d365bacpac.ps1#L217

Replace ; with linebreaks instead. ;-)

**Comment by Splaxi** [comment]
It is a act of balancing, because we also have some rather big cmdlets because of all the checking and messaging that we want to support. 

So bloating the cmdlet with multiple lines just for assigning to a hashtable, and afterwards use that for splatting the parameters for the function is a question of taste.

We could settle on multiple assignments per line, and then end up with 2-3 lines, instead of 6 lines.
Are you up for the task, feel free to fix it with a PR :)

**Comment by skaue** [comment]
Sure. I'm gonna just add a cmdlet first, then I'll create a PR.
Change is put in https://github.com/skaue/d365fo.tools/commit/ff926a88f0c19fffc3899207f2b51103a8ef8c29
