### ISSUE TITLE
Restart-D365Environment should be executed as Administrator

### ISSUE THREAD

**Issue by valerymoskalenko** [d365collaborative/d365fo.tools#432]
Restart-D365Environment should be executed with administrative privileges. Only then it makes a restart.
Please find details on the picture below
![image](https://user-images.githubusercontent.com/22589392/83893622-d8886700-a758-11ea-9bbd-8ee8ba2476cb.png)

Probably, some other cmdlets have the same issue.

**Comment by Splaxi** [comment]
Thanks for reporting this!

The issue is that we need to support Tier1 hosted on Microsoft license (non admin) and azure hosted (admin).

When you run the command we can test if the user is admin or not, but because we have a scenario where some users are not admins, we don't want to fail based on that...

So for now, it is doing as intended, but it puts you in a situation where you need to make sure to know when the command requires admin or not. 

Personally I recommend always running as admin when on Azure hosted, then you don't hit by this.

**Comment by valerymoskalenko** [comment]
Agreed on "always running as admin when on Azure hosted". I just forget to do that today :-)
Could you add just a warning message?

**Comment by Splaxi** [comment]
I'll see what I can do - but no promises.

A little trick for you, is to do the following. Then you don't forget it going forward.

1. Right click on your PowerShell icon on the task pane.
2. Right click on the "Windows PowerShell" option.
3. Click on properties.
4. Click advanced.
5. Select the checkbox "Run As Administrator".

![image](https://user-images.githubusercontent.com/8750181/83950735-443c0400-a82d-11ea-9d3f-2f0ca5feeb30.png)

![image](https://user-images.githubusercontent.com/8750181/83950768-764d6600-a82d-11ea-9344-94ddc89467a4.png)

![image](https://user-images.githubusercontent.com/8750181/83950797-9f6df680-a82d-11ea-8877-8b8b250ac443.png)

You can do the same for the PowerShell icon saved in your start menu, then you lower the risks.

We do this on all developer machines, to make sure people don't forget about it. We also do it for Visual Studio, which also requires "Run As Administrator".
