### ISSUE TITLE
New-D365Bacpac - ..\140\DAC\bin\SqlPackage.exe not found

### ISSUE THREAD

**Issue by Weezul** [d365collaborative/d365fo.tools#478]
Error on new Dev VMs:
`The C:\Program Files (x86)\Microsoft SQL Server\140\DAC\bin\SqlPackage.exe path wasn't found. Please ensure the path exists and you have enough permission to access the path.
`
It does exist in 130, but for some reason is not found there. I did not debug the script attempting to find the executable, but since it is a standard Dev VM, I thought more people might have this problem.

**Comment by Splaxi** [comment]
Hi,

The reason is that Microsoft long ago skipped the built-in and currently recommends that you use the .net core version of the SqlPackage.exe.

Which is installed with the: 
```
Invoke-D365InstallSqlPackage
```

And when it is complete, it will have updated the path reference across the module. So when you run the `New-D365Bacpac` cmdlet, it will use the new path automatically.

**Comment by Splaxi** [comment]
@Weezul 

Did you get to take a look at it?

**Comment by Weezul** [comment]
@Splaxi 
Sorry for only getting back to you now, for some reason I missed the notification of your reply, and by the time of the post had already done it the"manual" way.

I have just tested it after running Invoke-D365InstallSqlPackage, and it works like a charm. Thanks!

**Comment by Splaxi** [comment]
Thanks for letting me know! You can always ping me on twitter to get my attention.
