### ISSUE TITLE
Consider migrating AzureRM to Az

### ISSUE THREAD

**Issue by gdelmee** [d365collaborative/d365fo.tools#530]
Following docs, AzureRM is outdated. Can you please consider to migrate to Az?

https://docs.microsoft.com/en-us/powershell/azure/migrate-from-azurerm-to-az

**Comment by Splaxi** [comment]
Hi @gdelmee 

As long as the default deployment from LCS isn't coming with all the dependencies and as long as the same goes for the download vhd dev box - that won't happen. 

We had a request for the same long time ago, you should be able to find it with the right search/keywords.

The reason is solely that I don't want to drown in support issues where I need to guide the-not-so-technical persons on how to get the module up and running. 

With that said, I'm happy to see if the April release will solve some of the issues we faced last time.

In the meantime, could you share what you are facing with your work, that can't be solved with the current module and it's dependencies?

**Comment by gdelmee** [comment]
Thanks for the feedback. I totally get your point on the LCS Azure VM/VHD.
I wanted to leverage the library to interact with LCS (start/stop VM, trigger backups, etc.) and we already moved to Az module.
I'll see to set Azure pipeline in between.

**Comment by Splaxi** [comment]
Closing this.

@gdelmee let me know if you need any assistance with the current module and it dependencies, in combination with your requirements. I might have a few tricks up my sleeve, to make it running anyway.
