### ISSUE TITLE
[QUESTION] How catch DBSync error

### ISSUE THREAD

**Issue by VincentVerweij** [d365collaborative/d365fo.tools#581]
Hi @Splaxi,

I currently am using the D365FO.Tools for refreshing my devbox at a daily basis via Azure DevOps.
I saw that the step for the database sync apparently failed, but still was reported in Azure DevOps as successful.
![image](https://user-images.githubusercontent.com/41574930/136517870-edd0b214-514e-406f-978f-c2de9bb263ce.png)

(don't bother the actual error of the sync as it was my fault and has been fixed already)

Now I couldn't find anything on the repo that points me on how to catch such errors, and it's probably easy, but still wanted to ask.
Is it a matter of catching the error code that is returned from the call and if it differs from 0, do a throw error?
What is the proper way to catch an error, if one occurs in PowerShell?
I guess this is not only applicable for the DBSync but for other errors as well.

Thanks already!

**Comment by Splaxi** [comment]
`Enable-D365Exception` should be in all tasks (PowerShell icons), where you use the d365fo.tools. Just in case.

The `$WarningPreference="Stop"` was just an example and inspiration.

**Comment by VincentVerweij** [comment]
@Splaxi I did perform some tests on this.

I had two tables that were not able to sync due to some duplicate keys it would throw.
When doing it via Visual Studio in a project, the output would give me that a duplicate key exists.
When doing a sync in Azure DevOps where the task has the following PowerShell lines in it:
```powershell
Enable-D365Exception
Invoke-D365DbSync -Verbose
```
It did not stop running until the default Azure DevOps job timeout was reached (3 hours).
The output that I did receive was the following:
```
2021-11-09T19:32:01.2178986Z VERBOSE: [19:32:01][Invoke-Process] Output and Error streams will be redirected (silence mode)
2021-11-09T19:32:01.2284139Z VERBOSE: [19:32:01][Invoke-Process] Starting the SyncEngine.exe
2021-11-09T22:27:09.1758986Z ##[error]The operation was canceled.
```

To make sure that the timeout was not causing it to fail, it did run the exact same lines on my local machine too.
There it ran for a whole night and it gave the same output with the exception of `The operation was canceled.`

When I killed the actual sync engine (process: `SyncEngine.exe`), it did gave me the error I was expecting:

![image](https://user-images.githubusercontent.com/41574930/141104789-7ed0337b-3826-4190-9b16-753e191456b3.png)

After fixing the error of the duplicates, the process did run fine again.

I don't really know whether this is something wrong in the tools, or the sync engine.

**Comment by Splaxi** [comment]
I'm not entirely sure myself. 

I'll see if I can find the time to poke around a bit... 🤔🤔

**Comment by VincentVerweij** [comment]
Hi @MatthieuHz 

I was not able to get further into this.
So no news from me.

Perhaps this is a question that can be asked more generally on the Yammer Dynamics Insider Feedback program?
A question to ask what the SyncEngine.exe will return, or won't.
That way Mötz has not have to figure this one out on his own.
Just my 2cents.

If you have some more information on that, you can post it in here and perhaps we can come up with a solution, what do you think?

**Comment by MatthieuHz** [comment]
Done 😉

Thank you Vincent !

**Comment by MatthieuHz** [comment]
Oh yeah, well done

Unfortunately, Invoke-Process in d365fo.tools is already working as they suggest


![image](https://user-images.githubusercontent.com/15634271/153500749-831d939f-0462-4b4d-8ea9-dc4c82999864.png)

**Comment by Splaxi** [comment]
If you could try to pull out the needed code from both functions and do some local testing - you might be able to try different things. 

The showed code only works if the ShowOriginalProgress ISN'T true

We know that we are wrapping things in the module and there might be a missing configuration - in combination with the syncengine not behaving like normal executables - which gives us this error state. 

What happens if you call the syncengine directly from cmd?
From powershell? 
Using the standard invoke cmdlet in powershell?

**Comment by MatthieuHz** [comment]
@Splaxi 

I've tried this : 
cmd (C:\AOSService\PackagesLocalDirectory\bin>.\SyncEngine.exe -syncmode=fullall -verbosity=normal -metadatabinaries="C:\AOSService\PackagesLocalDirectory" -connect="server=localhost;Database=AxDB; User Id=axdbadmin;Password=axdbadminPassword;") -> It's working

PowerShell (same command line than before) -> It's working

Invoke command (Start-Process -FilePath C:\AOSService\PackagesLocalDirectory\bin\SyncEngine.exe -ArgumentList '-syncmode=fullall -verbosity=normal -metadatabinaries="C:\AOSService\PackagesLocalDirectory" -connect="server=localhost;Database=AxDB; User Id =axdbadmin;Password=axdbadminPassword;"') -> Not sure is the correct command but it's working too

So maybe, Invoke-Process is not the correct command for the synchronization through PowerShell

Thank you !

**Comment by Splaxi** [comment]
When you say working:

Like it behaves as expected or that it runs, when there isn't any errors?

**Comment by Splaxi** [comment]
So - should we re-visit this one?

Do we need to deep dive into some dirty testing, so we can get things to work properly?

@MatthieuHz & @VincentVerweij  Could you share some code / changes, that will give an error that shows when things DON'T work like expected, with the tools? Just a simple model / project or directly extension I can throw into an environment, to get me started?

**Comment by MatthieuHz** [comment]
Hi @Splaxi ;)

Here is what I have tested to make synchronization failed correctly

First, I'm on Onebox environment, with Microsoft default data (USMF ...)

You'll have to delete an index in a table (I choose SysServerConfig) thought SQL

![image](https://user-images.githubusercontent.com/15634271/158017393-43de9533-98c2-48a3-a623-6be2d422e2b7.png)

After you do this, duplicate the row in this same table 

![image](https://user-images.githubusercontent.com/15634271/158017426-5cb3b0bc-d0ac-44ad-9a1f-12788fe76741.png)

Next, you can try to synchronize your database, it will throw you an error

I try to use the Invoke-D365DbSync from D365fo.tools first 

![image](https://user-images.githubusercontent.com/15634271/158017487-8f419e96-fcb9-4865-9f79-84d64c6d9eb2.png)

Unfortunately, the function never ends and won't stop synchronization

![image](https://user-images.githubusercontent.com/15634271/158017505-ba9bee17-dd9b-4b6e-835d-9cdd450a97d2.png)

So I killed the process using Task Manager and the log appears in the PowerShell Window

![image](https://user-images.githubusercontent.com/15634271/158017528-75015aab-5a14-4e63-9e40-198fc4ea8a07.png)

So I made this little script that reproduce what Invoke-D365DbSync does by changing Invoke-Process with Start-Process (you'll have to change txt extension in ps1)

[TestSync.txt](https://github.com/d365collaborative/d365fo.tools/files/8237580/TestSync.txt)

![image](https://user-images.githubusercontent.com/15634271/158017597-5e269ef5-e607-45ad-b36a-f12badc8643c.png)

With this, you got a full log and SyncEngine.exe stopped after synchronization failed

![image](https://user-images.githubusercontent.com/15634271/158017626-4c248264-e995-472f-8910-1c3311693bc1.png)

I'm not sure of the result and the way to test it but it's a start

Hope it's enough to test on your side

Thanks again !

**Comment by Splaxi** [comment]
Thank you 🤘

This is enough to get me started and I appreciate that you took the time to reproduce it like this - super helpful 👍

**Comment by MatthieuHz** [comment]
I @Splaxi 🙂 

Have you made progress on this issue ? 

Thank you for your time

**Comment by FH-Inway** [comment]
@MatthieuHz I tried to reproduce your repro, no luck so far. Since the issue seems to be caused by the size of the output, it may not always happen. When did you last test this?

We should also compare our setups. For my part, I used two different local VHD environments, one on a vanilla 10.0.24 and one updated to the latest 10.0.29 preview. Both have the demo data (Contoso) databases. I also caused the sync error by adding a duplicate record in `SysServerConfig` after removing the index.

Since your repro indicates that replacing `Invoke-Process` with `Start-Process` works for you, one solution could be to add an optional switch parameter `-UseStartProcess` to the [Invoke-D365DbSync]() cmdlet. If the parameter is set, `Start-Process` instead of `Invoke-Process` would be used to call the sync engine.

**Comment by MatthieuHz** [comment]
Hi @FH-Inway 

Weird that you are not able to reproduce the endless synchronization

I've just test it on a 10.0.28 (last GA version for now) and it keeps loading endlessly when I use Invoke-D365DbSync function

I think we should try to use Start-Process, you are right

@Splaxi, could you please update the function by adding the parameter and use Start-Process instead of Invoke-Process as FH-Inway says ?

Thank you both 🙂

**Comment by Splaxi** [comment]
SO - I finally got my head into the details of this.

Looking at the internal code
https://github.com/d365collaborative/d365fo.tools/blob/6bc0c25fd5f035568f63f8e4df0a3f1b7e30d818/d365fo.tools/internal/functions/invoke-process.ps1#L108-L112

and reading this small comment on one of the MANY posts about issues with Start-Process:

https://stackoverflow.com/a/73454991/2678467

Could one of you guys try to implement that into the code and run your tests again?

```
 if (-not $ShowOriginalProgress) {
        $stderr = $p.StandardError.ReadToEnd()

        if ([system.string]::IsNullOrEmpty($stderr)) {
            $stdout = $p.StandardOutput.ReadToEnd()
        }
    }
```

My current gut tells me that because the syncengine **fails** - there isn't any output available. But looking at several other post, people are talking about the internal buffer is WAY to small, and that we need to read from it in an async way. Implementing that in powershell is going to be somewhat tricky. But let's see what we can end up with.

Please remember that Invoke-Process is a custom function, inside the tools - that we created, to counter the drawbacks from the Start-Process. That is the main reason why I haven't just released a version using Start-Process, because that could have some side-effects that I'm not willing to handle - for now.

If we can't come up with a working solution - then I'm ready to revisit the -UseStartProcess approach. I'm going to deploy a local box, and make it possible for me to easily reproduce the issue. Then we can try different things together and see if we can nail this for good.

**Comment by Splaxi** [comment]
And it seems that other people have been facing this before us:
https://stackoverflow.com/questions/24370814/how-to-capture-process-output-asynchronously-in-powershell/24371479#24371479

**Comment by Splaxi** [comment]
Initial testing - only with notepad.exe - this could be the real deal:

https://stackoverflow.com/a/36539226/2678467

**Comment by Splaxi** [comment]
For anyone trying to replicate and don't wanting to do the manual work
```
USE [AxDB]
SELECT * FROM SysServerConfig

ALTER TABLE [dbo].[SYSSERVERCONFIG] DROP CONSTRAINT [I_2363SERVERID] WITH ( ONLINE = OFF )

INSERT INTO SysServerConfig([SERVERID], [AZUREDEPLOYMENTID], [CLUSTERREFRECID], [ENABLEBATCH], [ISROLEIDLE], [LOADBALANCINGENABLED], [MAXSESSIONS], [SERVERGUID], [TIMEALIVE], [RECVERSION], [RECID], [THROTTLINGENABLED], [THROTTLINGCPURESERVATIONLIMIT], [THROTTLINGMEMORYRESERVATIONLIMIT], [THROTTLINGSQLUTILIZATIONRESERVATIONLIMIT])
SELECT * FROM SysServerConfig

SELECT * FROM SysServerConfig
```

**Comment by Splaxi** [comment]
Initial testing is promising!

I tried with the current implementation and it was stuck for more than 1 hour. Implemented the task based, async version, and ran it once again.

It behaved as we expected. A fix should be available tonight.

**Comment by Splaxi** [comment]
https://www.powershellgallery.com/packages/d365fo.tools/0.6.76

Grab the 0.6.76 and take it for a spin!

**Comment by VincentVerweij** [comment]
Although I left the FinOps scene (hence was unable to further assist), I am happy to see that this issue got fixed. Thanks to @Splaxi for fixing it and @MatthieuHz for providing information on your findings. Have a good one guys, and enjoy the new updated D365FO.Tools.

**Comment by Splaxi** [comment]
@VincentVerweij 
What scene are you hanging around in these days then? Curious to see what different paths people are taking.

If you are on Twitter, just tweet or DM me to keep in contact 🥳

**Comment by MatthieuHz** [comment]
Hi everyone !

I've just tested the update on a onebox and it works like a charm 

Thank you so much for your time @Splaxi !

Thank you to @VincentVerweij who started this subject and to @FH-Inway for your help 

Have a nice weekend !
