### ISSUE TITLE
Az.Storage changes in v0.7.0+ breaks AzureRM usage in existing scripts

### ISSUE THREAD

**Issue by batetech** [d365collaborative/d365fo.tools#749]
If you use AzureRM module in any PowerShell scripts on your dev VM, then recent d365fo.tools changes to add Az.Storage, which also installs Az.Accounts module, will break the ability to use AzureRM related scripts.  

For example: Connect-AzureRmAccount or Connect-AzAccount will both fail with the error: "Method 'get_SerializationSettings' in type 'Microsoft.Azure.Management.Internal.Resources.ResourceManagementClient' from assembly 'Microsoft.Azure.Commands.ResourceManager.Common, Version=4.0.0.0, Culture=neutral, 
PublicKeyToken=31bf3856ad364e35' does not have an implementation."

I updated d365fo.tools today and now my script used to automate our non-prod database restores is broken, the prior d365fo.tools version I had was 0.6.79. 

Since AzureRM is deprecated and going away Feb 2024, I don't expect this to be changed.  I'm just posting this for visibility for others in case they use AzureRM, and to find a workaround until I'm able to convert all my PowerShell scripts to use Az instead of AzureRM.

**Comment by batetech** [comment]
A workaround for this issue if you use AzureRM still is to uninstall d365fo.tools version 0.7.1, then uninstall the Az.Accounts and Az.Storage modules, and use d365fo.tools v 0.6.79 instead of the latest version until you replace AzureRM with Az in your scripts.

**The steps below are only if you use AzureRM within your own custom scripts outside of d365fo.tools.  Do not follow these steps if you use the Az module as it could break it.** 

To uninstall d365fo.tools v 0.7.1:
`Get-Module -Name d365fo.tools -ListAvailable | Where-Object -FilterScript {$_.Version -eq '0.7.1'} | Uninstall-Module -Force -Verbose`

To uninstall Az modules:
`Get-Module -Name Az.* -ListAvailable | Uninstall-Module -Force -Verbose -ErrorAction Continue`

To install d365fo.tools version 0.6.79: 
`Install-Module -Name d365fo.tools -RequiredVersion 0.6.79`

If you get an error uninstalling the Az modules of something like "_The version 'x' of module 'Az.*' is currently in use. Retry the operation after closing the applications._", then close PowerShell, then open task manager and kill other PowerShell or PowerShell ISE background tasks that are still open, and then try uninstalling the Az modules again. 

Then if you want to use Az alongside AzureRM, check out what is recommended here: https://learn.microsoft.com/en-us/powershell/azure/troubleshooting?view=azps-10.2.0#az-and-azurerm-coexistence

**Comment by FH-Inway** [comment]
Hi @batetech , good to see you here and thanks for reporting and providing a workaround. Awesome work!
I also like your thinking to raise awareness for others with this issue, but not expect a fix. Sorry for the breaking change.

Note that Azure.Storage was replaced by Az.Storage in version 0.7.0. Could you update the version number in the title of the issue? Since 0.7.0 was only for a short time the latest version, most people probably encounter the issue like you with 0.7.1, but just to avoid confusion.

We are also looking into getting rid of the Az.Storage dependency altogether, which would resolve this issue. If you (or anyone else) is interested, take a look at https://github.com/d365collaborative/d365fo.tools/issues/361#issuecomment-1627724985

@Splaxi Could you [pin the issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/pinning-an-issue-to-your-repository) to give it more visibility?

**Comment by FH-Inway** [comment]
Since we are not planning on addressing this issue directly and no other similar issues have been raised, I think this can be closed.
