### ISSUE TITLE
Invoke-D365AzCopyTransfer -ShowOriginalProgress = filename now ?

### ISSUE THREAD

**Issue by Simon-Syd** [d365collaborative/d365fo.tools#872]
hello,
I have few devops release with "-ShowOriginalProgress" parameters set to $true
so the command looks like : 

Invoke-D365AzCopyTransfer "C:\Users\simon\Downloads\myfile.jpg" "https://myblob.blob.core.windows.net/d365/AxDB.bacpac?sv=2XXXXXXX" -ShowOriginalProgress fotools

so I get : 
![image](https://github.com/user-attachments/assets/eff9a9aa-8991-4ddf-8f70-d53921c52b9b)
If i don't set/use the -ShowOriginalProgress, then it's fine

thanks for your help to fix that
I doubled check I'm using the latest d365fo.tools & Azcopy version

**Comment by FH-Inway** [comment]
Works for me with d365fo.tools 0.7.19 and azcopy 10.27.1, both with and without -ShowOriginalProgress.

I'm guessing you are not seeing the uploaded file in the Azure storage? The screenshot of the result log seems clipped, so it is hard to tell what the issue is.

Some more observations from my testing: Specifying the filename both in the destination uri and the Filename parameter will result in a "folder" with the filename from the uri and inside that folder, the file with the value of the Filename parameter is placed. Looks weird, but works.

ShowOriginalProgress also will output a line with information where an additional log can be found. Maybe that contains more information about what is going wrong?

I would also advise using named parameters, which makes PowerShell commands much easier to read and understand. E.g.
``` pwsh
Invoke-D365AzCopyTransfer -SourceUri "C:\users\simon\Downloads\myfile.jp" -DestinationUri "https://myblob.blob.core.windows.net/d365/AxDB.bacpac?sv=2XXXXXXX" -ShowOriginalProgress -FileName fotools
```
I was very confused when I first saw the original command :smile:
